version: "0.1.0"
service_configs:
  session:
    expire_time: 15552000000 # 180 days
    refreshable: false
  token:
    expire_time: 86400 # 1 day
    refresh_expire_time: 2592000 # 30 days
    registration_expire_time: 1800 # 30 minutes
  tags:
    create_undefined: true
    default_tag_icon: ""
    default_tag_color: ""
  user:
    hash_rounds: 12
